// Generated by https://quicktype.io

namespace TDAmeritrade.Services.Instruments.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Services.Instruments.Types;

    public partial class Instrument
    {
        [JsonProperty("cusip")]
        public string Cusip { get; set; }

        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("exchange")]
        public string Exchange { get; set; }

        [JsonProperty("assetType")]
        public AssetType AssetType{ get; set; }
    }
}
